# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ark-os   
# description will be included in the image's metadata
description: ARK OS delivers Brave, useful stuff and all Codecs you need out-of-the-box.

#  "kinoite-main" ist Fedora KDE inkl. RPM Fusion & Codecs!
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest  

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into your image's root folder /

  - type: os-release
    properties:
      NAME: "ARK OS"
      PRETTY_NAME: "ARK OS"
      VENDOR_NAME: "Jan Füllhase"
      VENDOR_URL: "https://github.com/Jan-Fuellhase/ARK-os"
      HOME_URL: "https://github.com/Jan-Fuellhase/ARK-os"
      BUG_REPORT_URL: "https://github.com/Jan-Fuellhase/ARK-os/issues"

  - type: rpm-ostree
    repos:
      # offizielles Brave-Repository  
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    keys:
      # Brave benötigt diesen Sicherheitsschlüssel
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    optfix:
      - brave.com # Repariert die Installationstrukur für Fedora Atomic
    install:
      - brave-browser # Installiert Brave direkt ins System-Image
    remove:
      # ARK entfernt Firefox, da ARK stattdessen Brave nutzen möchte 
      - firefox
      - firefox-langpacks 

  - type: default-flatpaks
    configurations:
      - notify: true # Sendet eine Benachrichtigung, wenn Flatpaks beim Update installiert werden
        scope: system
        # install: 
          # - org.videolan.VLC
          # - org.kde.kdenlive 
      - scope: user 

  # Standard-Hintergrundbild und Start-Symbol
  - type: script
    snippets:
      # Fedora-Standard-Wallpaper ersetzen
      - "rm -rf /usr/share/wallpapers/Fedora"
      - "ln -s /usr/share/wallpapers/ARK-OS /usr/share/wallpapers/Fedora"

      # Zusätzliche Kompatibilität mit älteren KDE-Versionen
      - "rm -rf /usr/share/wallpapers/Next"
      - "ln -s /usr/share/wallpapers/ARK-OS /usr/share/wallpapers/Next"

      # KDE-Startsymbol ersetzen
      # -print zeigt im Build-Log, welche Dateien gefunden wurden
      - "find /usr/share/icons/breeze /usr/share/icons/breeze-dark -name 'start-here-kde-plasma.svg' -print -exec cp --remove-destination /usr/share/icons/hicolor/scalable/places/start-here-kde-fedora.svg {} \\;"
  
  # WICHTIG: signing, dass ARK kryptografisch signiert wird.
  - type: signing
