# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ark-os   
# description will be included in the image's metadata
description: ARK OS delivers Brave, useful stuff and all Codecs you need out-of-the-box.

#  "kinoite-main" ist Fedora KDE inkl. RPM Fusion & Codecs!
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest  

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into your image's root folder /

  - type: os-release
    properties:
      NAME: "ARK OS"
      PRETTY_NAME: "ARK OS"
      VENDOR_NAME: "Jan Füllhase"
      VENDOR_URL: "https://github.com/Jan-Fuellhase/ARK-os"
      HOME_URL: "https://github.com/Jan-Fuellhase/ARK-os"
      BUG_REPORT_URL: "https://github.com/Jan-Fuellhase/ARK-os/issues"

  - type: rpm-ostree
    repos:
      # offizielles Brave-Repository  
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    keys:
      # Brave benötigt diesen Sicherheitsschlüssel
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    optfix:
      - brave.com # Repariert die Installationstrukur für Fedora Atomic
    install:
      - brave-browser # Installiert Brave direkt ins System-Image
    remove:
      # ARK entfernt Firefox, da ARK stattdessen Brave nutzen möchte 
      - firefox
      - firefox-langpacks 

  - type: default-flatpaks
    configurations:
      - notify: true # Sendet eine Benachrichtigung, wenn Flatpaks beim Update installiert werden
        scope: system
        # install: 
          # - org.videolan.VLC
          # - org.kde.kdenlive 
      - scope: user 

  # Standard-Hintergrundbild überschreiben
  - type: script
    snippets:
      # Entfernt den Standard-Wallpaper-Link von Fedora KDE
      - "rm -rf /usr/share/wallpapers/Next"
      # Setzt ARK-OS als neues Standard-Wallpaper für KDE
      - "ln -s /usr/share/wallpapers/ARK-OS /usr/share/wallpapers/Next"
      # SDDM Login-Screen (Standard-Fedora-Fallback)
      - "rm -f /usr/share/backgrounds/default.png"
      - "ln -s /usr/share/wallpapers/ARK-OS/contents/images/1920x1080.png /usr/share/backgrounds/default.png"

  # WICHTIG: signing, dass ARK kryptografisch signiert wird.
  - type: signing
