name: Build ISO
on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          image_name: ark-os
          image_repo: ghcr.io/jan-fuellhase
          image_tag: latest
          version: 44   # this may fix the pipeline
          iso_name: ark-os.iso

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v7
        with:
          name: ark-os-iso
          path: ${{ steps.build.outputs.iso_path }}/${{ steps.build.outputs.iso_name }}
